version: 2
jobs:
  test_ui:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run verify

  test_functions:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-serverless-{{ checksum "package.json" }}
      - run: npm install --prefix functions
      - save_cache:
          paths:
            - functions/node_modules
          key: v1-dependencies-serverless-{{ checksum "package.json" }}
      - run: npm run lint --prefix functions

  deploy:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm ci --prefix functions
      - run: npm run build
      - run:
          name: Update Firebase Config
          command: ./node_modules/.bin/firebase user=$MAIL_USER pass=$MAIL_PASS
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --force

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test_ui
      - test_functions
      - deploy:
          requires:
            - test_ui
            - test_functions
          filters:
            branches:
              only: master
